cruise-automation/mlir-tcp

- .bazelrc
- .github/workflows/bazelBuildAndTestTcp.yml
- README.md
OSX does not have lld by default.  Over time these build configs may need to diverge even more.
> Create separate build configs for linux & osx

- BUILD
- deps.bzl
- include/Pipeline/Pipeline.h
- lib/Pipeline/Pipeline.cpp
- test/BUILD
- test/basic_tcp_ops.mlir
- test/test_aot_compiled_basic_tcp_ops.cpp
- tools/aot/BUILD
- tools/aot/abi.h
- tools/aot/aot_compile.bzl
- tools/tcp-opt/tcp-opt.cpp
For now I think it will help in writing execution tests.  Longer term we may find other uses for it.
Here are the changes I made:
1. I added a `-lower-tcp-to-llvm` pass pipeline.
2. Created a genrule based macro that invokes `tcp-opt`, `mlir-translate` & `llc` to generate the CPU binary.
3. Added some tests.
> Add a tool to AOT compile TCP snippets into CPU binaries

- .github/workflows/bazelBuildAndTestTcp.yml
To allow early failures especially since builds can take a lot longer.
> [CI] Move clang-format and buildifer steps before build and test

- BUILD
- include/mlir-tcp/Dialect/IR/TcpBase.td
- lib/Conversion/TorchToTcp/TorchToTcp.cpp
This is idiomatic to usage in upstream MLIR. Includes other minor cleanup.
> Consolidate `TcpOpsIncGen` to include attrdef and enum decls/defs

- include/mlir-tcp/Conversion/Passes.h
- include/mlir-tcp/Dialect/IR/TcpBase.td
- include/mlir-tcp/Dialect/IR/TcpOps.td
- include/mlir-tcp/Dialect/IR/TcpTypes.td
- include/mlir-tcp/Dialect/Transforms/Passes.h
- lib/Conversion/Passes.cpp
- lib/Dialect/Transforms/Passes.cpp
- lib/InitAll.cpp
- No longer a constraint; fixes `error: 'tcp.isolated_group' op expects parent op to be one of 'func.func, tcp.group, tcp.isolated_group'`
- Used downstream; fixes `error: dialect 'tcp' provides no type parsing hook`
- Fixes `ld.lld: error: undefined symbol: mlir::tcp::TcpDialect::printType(mlir::Type, mlir::DialectAsmPrinter&) const` `referenced by TcpDialect.cpp`
> [Dialect] Traits and type parser/printer fixes to unblock downstream integrations

- BUILD
- include/mlir-tcp/Conversion/Passes.td
- include/mlir-tcp/Conversion/TorchToTcp/TorchToTcp.h
- lib/Conversion/TorchToTcp/DataMovement.cpp
- lib/Conversion/TorchToTcp/Elementwise.cpp
- lib/Conversion/TorchToTcp/Misc.cpp
- lib/Conversion/TorchToTcp/PopulatePatterns.h
- lib/Conversion/TorchToTcp/TorchToTcp.cpp
- lib/Conversion/TorchToTcp/Utils.h
- lib/Pipeline/Pipeline.cpp
- test/Conversion/TorchToTcp/partial_conversion.mlir
Add pass option to TorchToTcp accepting a set of op name strings as whitelist (for selective conversion). This allows flexibility with phase ordering of conversion passes in downstream pipelines.
> Allow partial `TorchToTcp` conversions using a whitelist

- include/mlir-tcp/Conversion/Passes.td
- include/mlir-tcp/Conversion/TorchToTcp/TorchToTcp.h
- lib/Conversion/TorchToTcp/TorchToTcp.cpp
- lib/Pipeline/Pipeline.cpp
Slightly improves user-interface by allowing pipelines to add the default ConvertTorchToTcpPass without an empty ArrayRef:
```
-  pm.addNestedPass<func::FuncOp>(tcp::createConvertTorchToTcpPass({}));
+  pm.addNestedPass<func::FuncOp>(tcp::createConvertTorchToTcpPass());
```
> Add default call to `createConvertTorchToTcpPass`

- BUILD
- include/mlir-tcp/Conversion/Passes.td
- include/mlir-tcp/Conversion/TorchToTcp/TorchToTcp.h
- include/mlir-tcp/Conversion/TorchToTcp/TorchToTcpCustomOp.h
- lib/Conversion/Passes.cpp
- lib/Conversion/TorchToTcp/TorchToTcpCustomOp.cpp
- test/Conversion/TorchToTcp/tcp_custom_ops.mlir
This allows switching between codegen vs kernels approaches, for torch ops that can lower to either tcp ops (codegen) or tcp.custom_op (kernel). Addresses https://github.com/cruise-automation/mlir-tcp/pull/17#discussion_r1382303711 using [Option 2](https://github.com/cruise-automation/mlir-tcp/pull/17#discussion_r1382436616).
> Separate conversion pass for `torch -> tcp.custom_op` to support both kernel and codegen approaches

- BUILD
- include/mlir-tcp/Dialect/Transforms/FusionPatterns.h
- lib/Dialect/Transforms/FuseTcpOpsPass.cpp
- lib/Dialect/Transforms/FusionPatterns.cpp
Move bottom up fuser declaration to header file
No testing required since it's a minor restructuring
> Move bottom up fuser declaration to header file

- lib/Conversion/TorchToTcp/TcpCustomOp.cpp
- lib/Conversion/TorchToTcp/Utils.h
- test/Conversion/TorchToTcp/tcp_custom_ops.mlir
As titled, lower torch transposed convolution to a custom TCP op to avoid a mis-compilation in `TorchToTosa`.
> Lower torch transposed convolution to a custom TCP op

- .bazelrc
- README.md
- docker/Dockerfile
Co-Contributors: @AaronStGeorge
> Add Debugging Guide

- .github/workflows/bazelBuildAndTestLlvm.yml
- .github/workflows/bazelBuildAndTestStablehlo.yml
- .github/workflows/bazelBuildAndTestTcp.yml
- .github/workflows/bazelBuildAndTestTorchmlir.yml
- WORKSPACE
- docker/Dockerfile
- docker/run_docker.sh
Running docker as root has unintended side effects such as clobbering of user space with root-modified files (e.g. when clang-format or buildifier was run from within docker). This also creates permission issues when generating compilation database (for clangd). Another side benefit of this is we no longer need the patches to our GHA/CI workflows to update bazel cache permissions before / after the builds.
> [Build] Switch all docker flows to run as user (non-root)

- .bazelrc
- .github/workflows/bazelBuildAndTestTcp.yml
- .gitignore
- .vscode/settings.json
- BUILD
- README.md
- WORKSPACE
- docker/Dockerfile
- tools/buildifier/BUILD
- tools/clangd/BUILD
Uses [bazel-compile-commands-extractor](https://github.com/hedronvision/bazel-compile-commands-extractor) to generate the compilation database from our bazel build. 
Other minor improvements include:
- simplify .bazelrc
- move buildifier and compile-commands-extractor targets to separate `tools/` to make downstream integrations easier (else they fail on loading these deps)
- bump bazel to 6.4.0 (for `--noenable_bzlmod` option)
> Support clangd for code completion, navigation and insights

- lib/Conversion/TorchToTcp/Misc.cpp
- test/Conversion/TorchToTcp/misc.mlir
Lowering `aten.size.int` op to `tensor::dim` op during torch-to-tcp.
Test (in docker):
`bazel test //test/...`
> [TorchToTcp] lowering support for aten.size.int op

- docs/gather.md
This PR proposes a design for gather ops in TCP.
> Design of Gather ops

- .github/workflows/bazelBuildAndTestLlvm.yml
- .github/workflows/bazelBuildAndTestStablehlo.yml
- .github/workflows/bazelBuildAndTestTorchmlir.yml
We're hitting `no space left on device` errors during llvm and stablehlo builds with the free GitHub hosted runners, which come with limited disk space allocations. Cleaning up the runners as recommended [here](https://github.com/orgs/community/discussions/25678), [here](https://github.com/orgs/community/discussions/26351) and https://github.com/actions/runner-images/issues/2875 have helped partially (increase root mount from 20G to 47G) but it still isn't enough for some builds. Temporarily disable the 3p builds on push to main (they will still run as non-merge gating on PRs), and re-enable once self-hosted runners are setup.
> Disable third party builds (on push to main) until we migrate to self-hosted runners

- test/AotCompile/BUILD
- test/BUILD
- tools/clangd/BUILD
Keeps the main test/BUILD specific to LIT, and allows (as a follow-on) expanding AotCompile into e2e integration style tests for TCP based compilations.
> Move AotCompile to its own BUILD

- test/AotCompile/test_aot_compiled_basic_tcp_ops.cpp
> Deallocate memref result after AOT test

- test/AotCompile/BUILD
- test/AotCompile/test_aot_compiled_basic_tcp_ops.cpp
- tools/aot/abi.h
> [AOT Compile] Use `StridedMemRefType` descriptor from upstream mlir/CRunnerUtils.h

- deps.bzl
[LLVM](https://github.com/llvm/llvm-project/tree/e5ed7b6e2fd368b722b6359556cd0125881e7638) (Feb 27)
[StableHlo](https://github.com/openxla/stablehlo/tree/d214e2e2bd568a80a9f25515907b64dd7b98c538) (March 5)**
[Torch-MLIR](https://github.com/llvm/torch-mlir/tree/a86e89ecb5c7929a39a38743fb7cacadf1ff41bb) (Mar 4)
DONE:
> [LLVM Integrate] Bump llvm, torch-mlir, stablehlo

- .github/workflows/bazelBuildAndTestTcp.yml
- .gitignore
- README.md
- deps.bzl
- requirements.txt
- requirements_lock.txt
- test/AotCompile/BUILD
- test/AotCompile/add_mul_loader_lib.py
- test/AotCompile/basic_tcp_ops_compile_execute_test.cpp
- test/BUILD
- test/lit.cfg.py
- test/python/BUILD
- test/python/fx_import/basic_test.py
- test/python_lit/fx_import/basic_test.py
- third_party/BUILD
- third_party/cnpy.BUILD
- tools/aot/BUILD
- tools/aot/README.md
- tools/aot/abi.h
- tools/aot/aot_compile.bzl
- tools/aot/execute_test.template.cpp
- tools/aot/execute_test_generator.py
- tools/aot/torch_exporter_harness.py
- tools/aot/torch_loader_utils.py
- tools/clangd/BUILD
- https://github.com/cruise-automation/mlir-tcp/pull/46/commits/ada575353cd2381504447c93bc204773134a9fc2: *[Please review]* AOT compile flow for TD export + TCP compilation and CPU codegen
- https://github.com/cruise-automation/mlir-tcp/pull/46/commits/75031b6aad77aa11a53909293c22b00a24d74cd0: *[Please skim]* AOT README (also pasted as PR description below)
- https://github.com/cruise-automation/mlir-tcp/pull/46/commits/705aeba4b65db3a676667d87642acd910c8488f1: *[Please skip]* NFC / mechanical changes
Inlining `tools/aot/README.md` below for readability.
-------
AOT Compile (Developer Guide)
=============================
The [`aot_compile`](https://github.com/cruise-automation/mlir-tcp/blob/main/tools/aot/aot_compile.bzl) bazel macro implements an end-to-end framework to compile PyTorch …
> [AOT Compile] E2E compile->execute->test framework using TorchDynamo export, TCP compilation, CPU codegen

- test/AotCompile/BUILD
- test/AotCompile/model_loader_lib.py
For the included tensor slice example, this is the Dynamo exported Torch dialect:
```ll
module {                                                                                                                                                 
func.func @func_main(%arg0: !torch.vtensor<[?,3],f32>) -> !torch.vtensor<[2,1],f32> {                                                                  
%int0 = torch.constant.int 0                                                                                                                         
%int0_0 = torch.constant.int 0                                                                                                                       
%int2 = torch.constant.int 2 …
```
> [AOT] Add tensor slicing to the aot_compile suite

- lib/Conversion/StablehloToTcp/StablehloToTcp.cpp
- lib/Conversion/TcpToArith/TcpToArith.cpp
- lib/Conversion/TcpToLinalg/Elementwise.cpp
- test/Conversion/TcpToLinalg/misc.mlir
TcpToLinalg conversion previously marked Tcp dialect as illegal, despite doing a partial conversion. So if there are any leftover Tcp ops after TcpToLinalg, they'd fail legalization (e.g. `tcp.const`). This is not correct and this partial conversion should only mark the Tcp ops it does convert as illegal. This PR fixes that.
> TcpToLinalg legality fixes: Mark only the Tcp ops with conversions as illegal

- lib/Conversion/StablehloToTcp/StablehloToTcp.cpp
- lib/Conversion/TcpToArith/TcpToArith.cpp
- lib/Conversion/TorchToTcp/Elementwise.cpp
- lib/Dialect/Transforms/FusionPatterns.cpp
- lib/Dialect/Transforms/IsolateGroupOpsPass.cpp
- [StablehloToTcp] Don't mark entire stablehlo dialect illegal; instead only mark the ops being converted illegal.
- [TcpToArith] Mark `tcp::ConstOp` illegal.
- [NFC] Minor code consistency cleanup
> More legality fixes in dialect conversions + code consistency cleanup

- requirements_lock.txt
- test/AotCompile/model_loader_lib.py
- tools/aot/torch_exporter_harness.py
- tools/aot/torch_loader_utils.py
`constraints` was soft-deprecated for a while now, superseded by `dynamic_shapes` but https://github.com/pytorch/pytorch/pull/120860 hard-deprecates it. This PR adopts the new API and pulls in torch-mlir fixes: https://github.com/llvm/torch-mlir/pull/3026.
> Adopt new dynamic_shapes API from torch.export

- lib/Pipeline/Pipeline.cpp
- test/AotCompile/BUILD
- test/AotCompile/model_loader_lib.py
This required two fixes to get working:
1. FIx legality conditions in TcpToLinalg (https://github.com/cruise-automation/mlir-tcp/pull/54)
2. Add arith-bufferize pass in our pipeline (this PR)
Torch dialect program:
```ll
module {                                                                                                                                                                                                                                                                
func.func @func_main(%arg0: !torch.vtensor<[?,3],f32>, %arg1: !torch.vtensor<[?,3],f32>) -> !torch.vtensor<[?,3],f32> {                                                                                                                                               
%int2 = torch.constant.int 2 …
```
> [AOT] Support `aten.add.Tensor` with `alpha`, and bufferize arith ops in llvm lowering

- test/Dialect/decompose_tensor_ops.mlir
The lit test was missed in https://github.com/cruise-automation/mlir-tcp/pull/50 which added the pass to decompose tensor concat ops and only included AOT e2e tests.
> LIT test for `decompose-tensor-ops` pass

- lib/Conversion/TorchToTcp/Misc.cpp
- test/AotCompile/BUILD
- test/AotCompile/model_loader_lib.py
- test/Conversion/TorchToTcp/misc.mlir
`torch.broadcast_to` when exported using dynamo generates an `aten.expand` op (not `aten.broadcast_to`):
```ll
module {                                                                                                                                                                                          
func.func @func_main(%arg0: !torch.vtensor<[1,2],f32>) -> !torch.vtensor<[3,2],f32> {                                                                                                           
%int3 = torch.constant.int 3                                                                                                                                                                  
%int2 = torch.constant.int 2 …
```
> [TorchToTcp] [AOT] Lower `aten.expand` op to `tcp.broadcast` 

- lib/Conversion/TorchToTcp/Misc.cpp
- lib/Dialect/IR/TcpOps.cpp
- test/AotCompile/BUILD
- test/Conversion/TorchToTcp/misc.mlir
- test/Dialect/misc.mlir
Ran into this a bug in Cruse internal repo, the changes here fix the issue. Here's an example of incorrect lowering:
```mlir
%4 = torch.aten.broadcast_to %3, %1 : !torch.vtensor<[1,2,1,2],f32>, !torch.list<int> -> !torch.vtensor<[4,2,4,2],f32>
```
was lowering to 
```mlir
%13 = tcp.broadcast %4, %6, %8, %10, %12 {axes = [0, 1, 2, 3]} : tensor<1x2x1x2xf32>, index, index, index, index -> tensor<4x2x4x2xf32>
```
axes 1 and 3 should not be broadcasted as those axes stay the same shape. The correct lowering is
```mlir
%13 = tcp.broadcast %4, %6, %10 {axes = [0, 2]} : tensor<1x2x1x2xf32>, index, index -> tensor<4x2x4x2xf32>
```
> [TorchToTcp] Don't broadcast axes that don't change size

- include/mlir-tcp/Dialect/IR/TcpOps.td
- lib/Conversion/TcpToLinalg/Elementwise.cpp
- lib/Conversion/TorchToTcp/Elementwise.cpp
- test/AotCompile/BUILD
- test/AotCompile/basic_tcp_ops.mlir
- test/AotCompile/basic_tcp_ops_compile_execute_test.cpp
- test/AotCompile/model_loader_lib.py
- test/Conversion/TcpToLinalg/unary.mlir
- test/Conversion/TorchToTcp/elementwise.mlir
- test/Dialect/unary.mlir
This PR adds two Tcp ops for rounding.
`tcp.round` - rounds the input value, with halfway cases rounded away from zero.
`tcp.round_even` - rounds in the input value, with halfway cases rounded to the nearest even integer.
This PR includes the following:
* The definition of the two ops in Tcp for rounding.
* Lowering from TorchToTcp for the `torch.round` op.
* Lowerings from TcpToLinalg for both the Tcp rounding ops.
* Lit tests for the ops and their lowerings.
* AOT tests for both the Tcp rounding ops.
Since `torch.round` rounds halfway cases to even, it maps directly to `tcp.round_even`. There is no direct way to represent the other case (rounding away from zero) in PyTorch. 
The AOT test for `tcp.round_even` is through `torch.round`, whereas the AOT test for `tcp.round` is from a Tcp IR …
> Add ops for rounding

- BUILD
- docs/gather.md
- include/mlir-tcp/Dialect/IR/TcpOps.td
- include/mlir-tcp/Dialect/IR/TcpTypes.td
- lib/Conversion/TcpToLinalg/DataMovement.cpp
- lib/Conversion/TcpToLinalg/PopulatePatterns.h
- lib/Conversion/TcpToLinalg/TcpToLinalg.cpp
- lib/Conversion/TorchToTcp/DataMovement.cpp
- test/AotCompile/BUILD
- test/AotCompile/model_loader_lib.py
- test/Conversion/TcpToLinalg/data_movement.mlir
- test/Conversion/TorchToTcp/data_movement.mlir
- test/Dialect/data_movement.mlir
- test/Pipeline/torch_to_tcp_pipeline.mlir
This PR adds the `tcp.gather` op. The design and semantics of this op are defined in [docs/gather.md](https://github.com/cruise-automation/mlir-tcp/blob/main/docs/gather.md).
More specifically, this PR includes:
* The definition of the `tcp.gather` op.
* Lowering from Torch to Tcp for the `torch.gather` op.
* Lowering from Tcp to Linalg for the `tcp.gather` op.
* Lit tests for the op and the lowerings.
* AOT test the Tcp gather op.
* Renames the op in the design document.
This PR does not update the lowering we have from aten.gather to tcp.custom("aten.gather") pattern [here](https://github.com/cruise-automation/mlir-tcp/blob/b812717001121df6974687e2b2e7e82b900390dd/lib/Conversion/TorchToTcp/TcpCustomOp.cpp#L29-L45). We should be able to control how `aten.gather` gets lowered by fixing …
> Add op for Gather

- BUILD
- include/mlir-tcp/Conversion/Passes.td
- include/mlir-tcp/Conversion/TcpToTensor/TcpToTensor.h
- include/mlir-tcp/Dialect/IR/TcpOps.td
- lib/Conversion/Passes.cpp
- lib/Conversion/TcpToTensor/TcpToTensor.cpp
- lib/Conversion/TorchToTcp/DataMovement.cpp
- lib/Pipeline/Pipeline.cpp
- test/Conversion/TcpToTensor/data_movement.mlir
- test/Conversion/TorchToTcp/data_movement.mlir
- test/Dialect/data_movement.mlir
This PR adds the `tcp.slice` op and the conversions needed for that op.
Specifically, this PR:
* Adds a new op in the Tcp dialect, `tcp.slice`.
* Updates the lowering of slice in TorchToTcp to create `tcp.slice`. Prior to this change, this lowering was emitting `tensor.extract_slice` instead.
* Adds a new lowering pass, `TcpToTensor`, which lowers `tcp.slice` to `tensor.extract_slice`.
* Adds unit tests and conversion tests for both the lowerings.
* Adds an e2e execution test that uses `tcp.slice`.
> Add tcp.slice op

- tools/clangd/BUILD
This was recently added (by https://github.com/cruise-automation/mlir-tcp/pull/72). In the future, we'll look into automating the target list generation (possibly a GitHub Action).
> [Clangd] Add TcpToTensor to clangd targets

- BUILD
- include/mlir-tcp/Dialect/IR/TcpTilingInterfaceImpl.h
- lib/Dialect/IR/TcpTilingInterfaceImpl.cpp
- lib/InitAll.cpp
- test/Dialect/structured_fuse.mlir
This PR adds an implementation of `TilingInterface` for the `tcp.slice` op. This is necessary to enable tile and fuse with `tcp.slice`.
> Tiling interface for slice op

- deps.bzl
[LLVM](https://github.com/llvm/llvm-project/tree/d16b21b17d13ecd88a068bb803df43e53d3b04ba)
[StableHlo](https://github.com/openxla/stablehlo/tree/d41390c3a731ba038e6363f75fcd135e6f727039)
[Torch-MLIR](https://github.com/llvm/torch-mlir/commit/0b46d1110aa9710a4c2935723c47dfe3d5c21fd3)
* There is no change on the StableHlo from torch-mlir upstream
> [LLVM Integrate] Bump llvm and torch-mlir

- BUILD
- include/mlir-tcp/Dialect/IR/TcpOps.td
- include/mlir-tcp/Dialect/Transforms/DropSymbolicShapeOpsPass.h
- include/mlir-tcp/Dialect/Transforms/Passes.td
- lib/Conversion/TorchToTcp/Misc.cpp
- lib/Dialect/IR/TcpOps.cpp
- lib/Dialect/Transforms/DropSymbolicShapeOpsPass.cpp
- lib/Dialect/Transforms/Passes.cpp
- lib/Pipeline/Pipeline.cpp
- test/Conversion/TorchToTcp/misc.mlir
- test/Dialect/canonicalize.mlir
- test/Dialect/drop_symbolic_shape_ops.mlir
- test/python_lit/fx_import/custom_op_test.py
- test/python_lit/fx_import/symbolic_shape_expr_test.py
- tools/aot/torch_exporter_harness.py
Support for TorchDynamo captured symbolic shape expressions was added to Torch-MLIR recently (https://github.com/llvm/torch-mlir/pull/3372). This PR continues the work to lower these to TCP.
> Symbolic shape expressions in TCP dialect

- requirements_lock.txt
- tools/aot/torch_exporter_harness.py
With https://github.com/llvm/torch-mlir/pull/3541 we can now intercept the Torch dialect during TorchDynamo export at two stages:
1. OutputType.RAW: This gets us the torch dialect as-imported from the FX graph
2. OutputType.TORCH: This gets us the torch dialect in backend compliant form, after the raw torch goes through DecomposeComplexOps and ReduceOpVariants.
We've been using 1 for all the AOT (e2e) tests, however this PR changes it to use 2, which is closer to the real backend lowering pipelines we use internally as well.
> [AOT] Use torch dialect in backend form instead of raw torch dialect

- lib/Dialect/Transforms/FusionPatterns.cpp
- test/Dialect/tcp_fusion.mlir
The current fusion algorithm does not handle `tcp.bind_symbolic_shape` ops very well because these ops cause an op to have multiple downstream uses. This change handles these ops "specially". We collect all the uses of an op which only specify the shape of the output into a separate use category. We then move the bind shape ops along with the original op if it was moved to another region.
> Handle `tcp.bind_symbolic_shape` ops in fusion algorithm

- lib/Conversion/TorchToTcp/TcpCustomOp.cpp
For fake_quantize_ops, `scale` and `zero_point` operands could be lowered by `TorchToTcp` already, so we need to relax the checking condition here (just need to make sure the type and shape are valid).
> update checking logic for scale and zp op

- lib/Dialect/Transforms/FusionPatterns.cpp
- test/Dialect/tcp_fusion.mlir
Revert the more aggressive multi-use fusion algorithm given that it has a correctness bug.
The newly added lit test demonstrates the correctness issue. 
The only part of the new algorithm which is retained is the special handling of `tcp.bind_symbolic_shape` ops.
> Revert multi-use fusion algorithm

- lib/Dialect/Transforms/FusionPatterns.cpp
- test/Dialect/tcp_fusion.mlir
As discussed, a small improvement to the fusion algorithm to account for the case when we have multiple uses of a definition but all those uses already belong to the group we are in. This allows us to fuse "diamond patterns" of multiple uses into a single group. See the update to the lit test for the improvement.
Note that this still is not a "maximal" fusion which can create groups with multiple returns etc.
> Slight improvement to fusion

- include/mlir-tcp/Dialect/Transforms/IsolateGroupOpsPass.h
- lib/Dialect/Transforms/IsolateGroupOpsPass.cpp
- test/Dialect/tcp_isolate_groups.mlir
A few small improvements to the `IsolateGroupOps` pass:
- Provide a hook to customize whether a const like op used in the `tcp.group` will get copied into the group or whether it will be passed in as an input argument. The main pass does always returns true so this is a non-functional change in `mlir-tcp`. 
- The previous version did not handle ops with contained regions and block arguments (such as an `scf.forall` inside the `tcp.group`). We now handle this (see updated lit test).
> Add support for customizing const inlining and ops with regions to IsolateGroupOps pass

- lib/Conversion/TorchToTcp/DataMovement.cpp
- lib/Conversion/TorchToTcp/Utils.cpp
- lib/Conversion/TorchToTcp/Utils.h
- test/AotCompile/BUILD
- test/AotCompile/model_loader_lib.py
- test/Conversion/TorchToTcp/data_movement.mlir
This PR add support for lowering `torch.index_select` to `tcp.gather`. The logic behind this lowering is documented [here](https://github.com/cruise-automation/mlir-tcp/blob/main/docs/gather.md#gather-slices-along-a-given-dim).
```
bazel test //test:Conversion/TorchToTcp/data_movement.mlir.test
bazel test //test/AotCompile:gather_slices_compile_execute_test
```
> Handle index_select by lowering it to tcp.gather

- lib/Conversion/TorchToTcp/Misc.cpp
- lib/Conversion/TorchToTcp/TcpCustomOp.cpp
- lib/InitAll.cpp
- test/Conversion/TorchToTcp/tcp_custom_ops.mlir
- Fix a minor issue with broadcast op (fold the broadcast if axes attr is empty)
- Add following ops to tcp.custom_op:
--`aten.sort`
--`aten.cumsum`
--`aten.min.dim`
--`aten.view`(dynamic shape only)
--`aten.topk`
To test:
`bazel test //...` (in docker)
> update custom op conversions

- lib/Conversion/TorchToTcp/Elementwise.cpp
- test/AotCompile/BUILD
- test/AotCompile/model_loader_lib.py
- test/Conversion/TorchToTcp/elementwise.mlir
Lower aten.log1p op to  tcp.log(tcp.add(input, 1.0))
To test:
`bazel test //...` (in docker)
> support lowering for aten.log1p

- lib/Conversion/TorchToTcp/TcpCustomOp.cpp
Only convert aten.view to tcp.custom_op when the `size` array is non-constant. The rest will be handled through torch-to-tosa.
TODO: send out an upstream PR to fix` tosa.reshape`  size calculation logic.
> relax aten.view conversion constraint 

- docker/Dockerfile
- include/mlir-tcp/Dialect/IR/TcpOps.td
- lib/Conversion/TorchToTcp/DataMovement.cpp
- lib/Conversion/TorchToTcp/Misc.cpp
- lib/Conversion/TorchToTcp/TcpCustomOp.cpp
- lib/Conversion/TorchToTcp/Utils.cpp
- lib/Dialect/IR/TcpOps.cpp
- test/AotCompile/BUILD
- test/AotCompile/model_loader_lib.py
- test/Conversion/TorchToTcp/data_movement.mlir
- test/Conversion/TorchToTcp/tcp_custom_ops.mlir
- tools/aot/aot_compile.bzl
* Add converter for index.Tensor_hacked_twin -> tcp.gather & tcp.broadcast
* Remove the  `tcp.custom_op` variants of `Tensor_hacked_twin`
* The Tcp variants do not have full coverage of the PyTorch, but we should seek to expand the coverage of our converters
* Fix tcp.const when it is a dense resource of ints to cast the value
* Add verifier for `tcp.gather` and `tcp.const` to ensure that is used correctly
> Add converter for index.Tensor_hacked_twin

- lib/Conversion/TorchToTcp/TcpCustomOp.cpp
- lib/Conversion/TorchToTcp/Utils.cpp
- lib/Conversion/TorchToTcp/Utils.h
- test/Conversion/TorchToTcp/tcp_custom_ops.mlir
tcp.custom_op support for` torch.aten.arange` with dynamic input. Static case will be handled through TOSA dialect.
To test:
(in docker)
`bazel test //...`
> tcp.custom_op support for torch.aten.arange with dynamic input

- include/mlir-tcp/Dialect/IR/TcpOps.td
- lib/Conversion/TcpToLinalg/DataMovement.cpp
- lib/Conversion/TorchToTcp/DataMovement.cpp
- lib/Conversion/TorchToTcp/Utils.cpp
- lib/Conversion/TorchToTcp/Utils.h
- lib/Dialect/IR/TcpOps.cpp
- test/Conversion/TcpToLinalg/data_movement.mlir
- test/Conversion/TorchToTcp/data_movement.mlir
Add tcp.gather_nd and rework index.Tensor_hacked_twin to use gather_nd
> Add tcp.gather_nd and rework index.Tensor_hacked_twin to use gather_nd
